### ISSUE TITLE
TypeError: argument 2 to map() must support iteration when running the image

### ISSUE THREAD

**Issue by songyunlu** [openai/kubernetes-ec2-autoscaler#16]
Hi OpenAI developers,

I am evaluating the project but running into the problem

```
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 78, in main
    scaled = cluster.scale_loop()
  File "/app/autoscaler/cluster.py", line 124, in scale_loop
    all_nodes = map(KubeNode, pykube.Node.objects(self.api))
TypeError: argument 2 to map() must support iteration
```

Could you please give me some hints how to solve the issue?

**Comment by vicki-c** [comment]
That generally means that we failed to fetch the list of nodes from Kube. You might want to check your configuration to see if the connection works (with the `--kubeconfig` flag). (I've pushed a change to make that message clearer!)

**Comment by songyunlu** [comment]
Thanks, @vicki-c 

I found that I assigned the wrong value to `PYKUBE_KUBERNETES_SERVICE_HOST` so that the connection to the service host could not be established.

The ReplicationController is up now.
